name: Periodic solutions update

on:
  push:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  download_new_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: update
        env:
          super_secret: ${{ secrets.CW_COOKIE }}
        run: |
          python main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master