name: Periodic solutions update

on:
  push:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  download_new_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
           uv pip install -r requirements.txt
      - name: update
        env:
          CW_COOKIE: ${{ secrets.CW_COOKIE }}
        run: |
          python main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'output/*.py'
          branch: master
          commit_message: Automated update